campaign/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views

app_name = 'campaign'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'item/(\d)/$', views.item, name = 'item'),
]

history/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "history"
urlpatterns = [
    path('index', views.index, name = "index"),
    path('user_email', views.history_webservice, name = "history"),
    path('', views.index, name = "index"),
]

home/urls.py
from django.urls import include, path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name = 'index'),
]

kelompok_d_tiga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('campaign/', include('campaign.urls')),
    path('news/', include('news.urls')),
    path('about/', include('comment.urls', namespace='about')),
    path('register/', include('register.urls')),
    path('history/', include('history.urls')),
    path('', include('home.urls')),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here

]

news/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from . import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'item/(\d+)/$', views.item, name = 'item'),
]

register/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import views
from .views import add_donate, login, logout


# Create your views here.
app_name = 'register'
urlpatterns = [
	url(r'add_donate/(\d)/$', add_donate, name = 'add_donate'),
	url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from campaign.models import campaign_item
from register.models import Donasi_models
from news.models import news_item

# Create your views here.
def index(request):
    response = {}
    response['location'] = 'Home'
    response['home_bar'] = 'active'
    response['campaign'] = campaign_item.objects.all()
    response['account'] = Donasi_models.objects.all()
    response['news'] = news_item.objects.all()[:3]
    response['donation'] = Donasi_models.objects.all().values('jumlah_donasi')
    response['total_campaign'] = len(response['campaign'])
    response['campaign'] = response['campaign'][:6]
    response['campaign_trend'] = response['campaign'][:2]
    response['total_account'] = len(response['account'])
    response['total_donation'] = sum([u['jumlah_donasi'] for u in response['donation']]) 

    html = 'index.html/'

    return render(request, html, response)

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{%static "css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{%static "css/bootstrap/bootstrap-grid.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{%static "css/style.css" %}">
    <title> {{ location }} </title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{%static "js/bootstrap.min.js" %}"></script>
    {% block head %}
    {% endblock %}
    <script src="{%static "js/about.js" %}"></script>
</head>
<body>
    <div id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <a class="navbar-brand" href="#">
                <h3>SinarPerak</h3>
            </a>
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="#">
                
                    <h5>Hello, {{ user.username }}</h5>
            </a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {{ home_bar }}">
                        <a class="nav-link" href="{% url 'home:index' %}"><h4>Home</h4><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {{ campaign_bar }}">
                        <a class="nav-link" href="{% url 'campaign:index' %}"><h4>Campaign</h4></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news:index' %}"><h4>News</h4></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about:index' %}"><h4>About</h4></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'history:index' %}"><h4>History</h4></a>
                    </li>
                    <li class="nav-item {{ register_bar }}">
                        <a class="nav-link" href="{% url 'register:logout' %}"><h4>Logout</h4></a>
                     </li>   
                    {% else %}
                    <li class="nav-item {{ register_bar }}">
                        <a class="nav-link" href="{% url 'register:login' %}"><h4>Login</h4></a>
                    </li>
                    {% endif %}

                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li> -->
                </ul>
            </div>
        </nav>
    </div>


        {% block main %}
        {% endblock %}
    

    <div id="footer" class="row padding-footer">
        <div class="col-md-2">

        </div>
        
        <div class="col-md-8 row">
            <div class="col-md-12 row border-bottom">
                <div class="col-md-7">
                    <h2>SinarPerak</h2>
                </div>
                <div class="col-md-5 no-padding align-middle align-self-center found-us">
                    Found us: 
                    <svg class="icon-margin" style="fill: #cd486b" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path d="M14.829 6.302c-.738-.034-.96-.04-2.829-.04s-2.09.007-2.828.04c-1.899.087-2.783.986-2.87 2.87-.033.738-.041.959-.041 2.828s.008 2.09.041 2.829c.087 1.879.967 2.783 2.87 2.87.737.033.959.041 2.828.041 1.87 0 2.091-.007 2.829-.041 1.899-.086 2.782-.988 2.87-2.87.033-.738.04-.96.04-2.829s-.007-2.09-.04-2.828c-.088-1.883-.973-2.783-2.87-2.87zm-2.829 9.293c-1.985 0-3.595-1.609-3.595-3.595 0-1.985 1.61-3.594 3.595-3.594s3.595 1.609 3.595 3.594c0 1.985-1.61 3.595-3.595 3.595zm3.737-6.491c-.464 0-.84-.376-.84-.84 0-.464.376-.84.84-.84.464 0 .84.376.84.84 0 .463-.376.84-.84.84zm-1.404 2.896c0 1.289-1.045 2.333-2.333 2.333s-2.333-1.044-2.333-2.333c0-1.289 1.045-2.333 2.333-2.333s2.333 1.044 2.333 2.333zm-2.333-12c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.958 14.886c-.115 2.545-1.532 3.955-4.071 4.072-.747.034-.986.042-2.887.042s-2.139-.008-2.886-.042c-2.544-.117-3.955-1.529-4.072-4.072-.034-.746-.042-.985-.042-2.886 0-1.901.008-2.139.042-2.886.117-2.544 1.529-3.955 4.072-4.071.747-.035.985-.043 2.886-.043s2.14.008 2.887.043c2.545.117 3.957 1.532 4.071 4.071.034.747.042.985.042 2.886 0 1.901-.008 2.14-.042 2.886z"/></svg>
                    <svg class="icon-margin" style="fill: #1dcaff" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.066 9.645c.183 4.04-2.83 8.544-8.164 8.544-1.622 0-3.131-.476-4.402-1.291 1.524.18 3.045-.244 4.252-1.189-1.256-.023-2.317-.854-2.684-1.995.451.086.895.061 1.298-.049-1.381-.278-2.335-1.522-2.304-2.853.388.215.83.344 1.301.359-1.279-.855-1.641-2.544-.889-3.835 1.416 1.738 3.533 2.881 5.92 3.001-.419-1.796.944-3.527 2.799-3.527.825 0 1.572.349 2.096.907.654-.128 1.27-.368 1.824-.697-.215.671-.67 1.233-1.263 1.589.581-.07 1.135-.224 1.649-.453-.384.578-.87 1.084-1.433 1.489z"/></svg>
                    <svg class="icon-margin" style="fill: #00c300" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill-rule="evenodd" clip-rule="evenodd"><path d="M12 0c-6.626 0-12 5.372-12 12 0 6.627 5.374 12 12 12 6.627 0 12-5.373 12-12 0-6.628-5.373-12-12-12zm7 11.681c0-3.133-3.14-5.681-7-5.681s-7 2.548-7 5.681c0 2.808 2.49 5.159 5.854 5.604.228.049.538.15.617.345.071.177.046.454.022.633l-.099.599c-.031.177-.141.692.606.378.747-.315 4.031-2.374 5.5-4.064 1.014-1.113 1.5-2.242 1.5-3.495zm-9.606 1.808h-1.961l-.095-.038-.001-.001-.003-.003-.038-.094v-3.05c0-.075.061-.136.137-.136h.491c.075 0 .136.061.136.136v2.422h1.334c.075.001.136.062.136.137v.491c0 .075-.061.136-.136.136zm7.275 0h-1.962l-.094-.038-.004-.004-.038-.094v-3.05l.038-.094.004-.004.094-.038h1.962c.075 0 .136.061.136.136v.491c0 .076-.061.137-.136.137h-1.334v.515h1.334c.075 0 .136.061.136.137v.491c0 .075-.061.136-.136.136h-1.334v.515h1.334c.075.001.136.062.136.137v.491c0 .075-.061.136-.136.136zm-6.091 0h-.491c-.076 0-.137-.061-.137-.136v-3.05c0-.075.061-.136.137-.136h.491c.075 0 .136.061.136.136v3.05c0 .075-.061.136-.136.136zm1.241 0h-.491c-.075 0-.137-.061-.137-.136v-3.05c0-.075.062-.136.137-.136h.491l.012.001.013.001.007.002.013.004.005.001.012.006.011.006.007.005.014.011.009.01.01.013 1.398 1.888v-1.812c0-.075.061-.136.136-.136h.491c.076 0 .137.061.137.136v3.05c0 .075-.061.136-.137.136h-.491l-.035-.004-.002-.001-.013-.004-.007-.003-.01-.005-.008-.006-.002-.001-.034-.033-1.4-1.89v1.811c0 .075-.061.136-.136.136z"/></svg>
                    <svg class="icon-margin" style="fill: #ff0000" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm4.441 16.892c-2.102.144-6.784.144-8.883 0-2.276-.156-2.541-1.27-2.558-4.892.017-3.629.285-4.736 2.558-4.892 2.099-.144 6.782-.144 8.883 0 2.277.156 2.541 1.27 2.559 4.892-.018 3.629-.285 4.736-2.559 4.892zm-6.441-7.234l4.917 2.338-4.917 2.346v-4.684z"/></svg>
                    <svg class="icon-margin" style="fill: #0077B5" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 16h-2v-6h2v6zm-1-6.891c-.607 0-1.1-.496-1.1-1.109 0-.612.492-1.109 1.1-1.109s1.1.497 1.1 1.109c0 .613-.493 1.109-1.1 1.109zm8 6.891h-1.998v-2.861c0-1.881-2.002-1.722-2.002 0v2.861h-2v-6h2v1.093c.872-1.616 4-1.736 4 1.548v3.359z"/></svg>
                </div>
            </div>
            <div class="col-md-12 row border-bottom footer-margin-top">
                <div class="col-md-3">
                    <p>
                        <b>SinarPerak</b> adalah sebuah platform
                        yang digunakan untuk menggalang
                        dana berbagai hal secara online
                    </p>
                    <p>
                        <b>Fakultas Ilmu Komputer</b>, <br>
                        Universitas Indonesia, <br>
                        Depok, Jawa Barat
                    </p>
                </div>
                <div class="col-md-1">
                    
                </div>
                <div class="col-md-2 footer-item-link">
                    <h5><b>Donate</b></h5>
                    <a href="#">Trending</a> 
                    <br>
                    <a href="#"">Newest</a>
                </div>
                <div class="col-md-2 footer-item-link">
                    <h5><b>News</b></h5>
                    <a href="#">Trending</a> 
                    <br>
                    <a href="#"">Newest</a>
                </div>
                <div class="col-md-2 footer-item-link">
                    <h5><b>How to Donate?</b></h5>
                    <a href="#">Text tutorial</a> 
                    <br>
                    <a href="#">Video Tutorial</a>
                </div>
                <div class="col-md-2 footer-item-link">
                    <h5><b>Connect Us</b></h5>
                    <a href="#">Chat us</a> 
                    <br>
                    <a href="#">Our team</a>
                    <br>
                    <a href="#">Blog</a>
                </div>
            </div>

            <div class="col-md-12 footer-margin-top text-center">
                <p>Copyright © 2018 PPW-D-3. All Rights Reserved</p>
            </div>

        </div>

        

        <div class="col-md-2">
            
        </div>

    </div>
    
</body>
</html>

home/templates/index.html
{% extends "base.html" %}

{% block main %}
{% load static %}
<div class="home-header row">
    <div class="col-md-12 row home-header-quote">
        <div class="col-md-2">

        </div>
        <div class="col-md-8 text-right">
            <h1>SinarPerak</h1>
            <h2>Tidak selamanya kita berkecukupan. Mari bantu yang membutuhkan.</h2>
            <div class="home-donate-button">
                <a class="btn btn-info button-self-style button-header-donate" role="button" href="{% url 'campaign:index' %}"> Donate Now</a>
            </div>
        </div>
        <div class="col-md-2">

        </div>
    </div>
    <div class="col-md-12 home-header-detail">
        <div class="row">
            <div class="col-md-2">

            </div>
            <div class="col-md-8 row text-center">
                <div class="col-md-4 total-donation">
                    <h1>Rp. {{ total_donation }}</h1>
                    <h2>Funding</h2>
                </div>
                <div class="col-md-4">
                    <h1> {{ total_campaign }} </h1>
                    <h2>Campaign</h2>
                </div>
                <div class="col-md-4">
                    <h1> {{ total_account}} </h1>
                    <h2>Good People</h2>
                </div>
            </div>
            <div class="col-md-2">
                
            </div>
        </div>
    </div>
</div>

<div class="home-campaign-section row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 row">
        <div class="col-md-12">
            <div class="campaign-title">
                <h1>Campaigns</h1>
            </div>
        </div>
        {% if campaign %}
        {% for campaign_item in campaign %}
        <div class="col-md-4 campaign-card text-center">

            <a href="{% url 'campaign:item' campaign_item.pk %}">

                <div class="item-campaign"  style="border-radius: 5px;">
                    <div class="header-card" style="background: url({{ campaign_item.imageurl }});
                        background-size: cover;">
                       
                    </div>
                    <div class="title-card">
                        <h4>{{ campaign_item.title }}</h4>
                    </div>
                    <div class="persen-card">

                        <h3></h3>

                    </div>
                    <div class="progress-card">
                        <progress max="100" value="54"></progress>
                    </div>
                    <div class="target-card">
                        <h5>Target</h5>
                        <h3>Rp {{ campaign_item.target }}</h3>
                    </div>
                </div>
            </a>
        </div>

        {% endfor %}
        
        <div class="col-md-12 text-center">
            <div class="home-campaign-button">
                <a style="color: #ffffff;" class="btn btn-info button-self-style home-find-out-more-button" role="button" href="{% url 'campaign:index' %}">Find out more</a>    
            </div>
        </div>
        {% else %}
        <div class="col-md-12 text-center" style="padding-bottom: 20px;">
            <h3 style="color: #bdc3c7;">Belum ada campaign</h3>
        </div>
        {% endif %}
        
    </div>
    <div class="col-md-2">
        
    </div>    
</div>

<div class="home-news-section row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 row">
        <div class="col-md-12">
            <div class="news-title">
                <h1>News</h1>
            </div>
        </div>
        {% if news %}
        {% for news_item in news %}
        {% if forloop.first %}
        <div class="col-md-6 text-center">
            <a href="{% url 'news:item' news_item.pk %}">
                <div class="big-news" style="background: linear-gradient(
                    rgba(0, 0, 0, 0.3), 
                    rgba(120, 224, 143, 0.3)), 
                    url({{ news_item.imageurl }});
                    background-size: cover;">
                    <div class="detail-big-news">
                        <h3> {{ news_item.title }} </h3>
                        <p> {{ news_item.details|truncatechars:120 }} </p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6 row">
        {% else %}
            <div class="col-md-12">
                <div class="card-news row">
                    <div class="col-4 head-img" style="background: url({{ news_item.imageurl }})">

                    </div>
                    <div class="col-8">
                            <h5>{{ news_item.title }}</h5> 
                            <p> {{ news_item.details|truncatechars:40}} </p>
                    </div>

                </div>
            </div>
        {% endif %}
        {% endfor %}
            <div class="col-md-12">
                <div class="news-trending-button">
                    <a style="color: #ffffff;" class="btn btn-info button-self-style news-find-out-more-button text-center" role="button" href="{% url 'news:index' %}">Find out more</a>    
                </div>
            </div>
        {% else %}
        <div class="col-md-12 text-center">
            <h3 style="color: #bdc3c7;">Belum ada berita</h3>
        </div>
        {% endif %}
        </div>
        
    </div>
    <div class="col-md-2">

    </div>

</div>

<div class="tutorial-section row"  style="padding-top: 30px; padding-bottom: 40px;">
    <div class="col-md-2">

    </div>
    <div class="col-md-8 row text-center">
        <div class="col-md-12 text-center"  style="padding-bottom: 40px;">
            <h1>How to donate?</h1>
        </div>
        <div class="col-md-4">
            <img class="head-tutorial" src="https://www.tailorsofdistinction.com.au/wp-content/uploads/2015/05/add-user.png"></img>
            <div class="detail-turorial" style="padding-top: 30px;">
                <p>Buat akun baru pada form registrasi yang ad apada menu login.</p>
            </div>
        </div>
        <div class="col-md-4">
            <img class="head-tutorial" src="https://images-fe.ssl-images-amazon.com/images/I/319oHBg4nuL.png"></img>
            <div class="detail-turorial" style="padding-top: 30px;">
                <p>Pilih menu campaign dan pilih campaign mana yang ingin anda danai</p>
            </div>
        </div>
        <div class="col-md-4">
            <img class="head-tutorial" src="https://bradan.co/wp-content/uploads/2017/01/icon-cash.png"></img>
            <div class="detail-turorial" style="padding-top: 30px;">
                <p>Lakukan pembayaran dengan cara transfer atau menggunakan kredit.</p>
            </div>
        </div>
    </div>
    <div class="col-md-2">

    </div>
</div>

{% endblock %}